### ISSUE TITLE
Problem kothay?

### ISSUE THREAD

**Issue by say4n** [garain/OpenCV-image-processing-projects#1]
Explain kor.

**Comment by say4n** [comment]
And suppose you have a 1D list and want to convert it to 2D list, the syntax in Python is:

 ```python3
>>> l = list(range(1,11))
>>> x = [[i] for i in l]
>>> l
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
>>> x
[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]
```

**Comment by garain** [comment]
import numpy as np
#import matplotlib as ml
#import matplotlib.pyplot as plt
from sklearn.linear_model import ARDRegression
array=[]
x=[]
k=[]
g=[]
b=[]
y=[]
p=[]
n=input()
j=0
#for i in range(n):
   # array.append(map( str, raw_input().split() ))
array=np.array([raw_input().split() for _ in range(n)],str)
for i in range (n):
    x.append(array[i][0])
    y.append(array[i][1])
for i in range (n):
    p.append(int(filter(str.isdigit,x[i])))#Extract numbers from string.
for i in range (n):
    k.append(p[i])
#To make the array 2 by n
#b=np.linalg.pinv(g.T)
#c=np.matmul(b,y)
y = [int(numeric_string) for numeric_string in y]
g=np.vstack((k,p,y))#To insert 2 1d arrays in a 2d array
b=g.T
#g=[(i,j) for i in k for j in p]
#from sklearn import svm
#clf = svm.SVC()
#clf.fit(b,y)  
c=[]
c1=[]
#np.reshape(p,(1,-1))
#p=np.array(p)
#print(p)
p = [[i] for i in p] 
for i in range (12):
    c.append(1)    
for i in range(12):
    c1.append(n+i+1)
c2=[]
c3=[]
c2=np.vstack((c1,c1))
c3=c2.T
clf = ARDRegression(compute_score=True)#Experiment with n_estimator value.Here its optimal value is 75
clf.fit(p,b[:,-1])
prediction=clf.predict(c3)

for i in prediction:
    print(i)
#print(clf.predict(c2.T))
#plt.scatter(p, y, c="r", alpha=1)
#plt.show()

**Comment by garain** [comment]
**# Eta output**

Traceback (most recent call last):
  File "solution.py", line 50, in <module>
    prediction=clf.predict(c3)
  File "/var/ml/python/local/lib/python2.7/site-packages/sklearn/linear_model/bayes.py", line 526, in predict
    y_mean = self._decision_function(X)
  File "/var/ml/python/local/lib/python2.7/site-packages/sklearn/linear_model/base.py", line 241, in _decision_function
    dense_output=True) + self.intercept_
  File "/var/ml/python/local/lib/python2.7/site-packages/sklearn/utils/extmath.py", line 140, in safe_sparse_dot
    return np.dot(a, b)
ValueError: shapes (12,2) and (1,) not aligned: 2 (dim 1) != 1 (dim 0)

**Comment by say4n** [comment]
Either upload the source file to the repo or format the comment otherwise, I can't read it!
(Do this, I'll get back to you tomorrow. Call me around 11am-ish.)

**Comment by garain** [comment]
Source code is traffic_forecast.py

**Comment by say4n** [comment]
Your code works for me. I have executed it [here](https://www.codechef.com/ide/)(set Cpython2.7 as language).
The inputs which I have used are:
```
5
1 2
3 4
5 6
7 8
9 10
```

And the corresponding output is:

```
6.9875
7.975
8.9625
9.95
10.9375
11.925
12.9125
13.9
14.8875
15.875
16.8625
17.85
```
